#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mocking_service
#    username: root
#    password:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
app:
  config:
    #    path: /config
    path: .\config